"""Unit tests for the deterministic gates, the pure logic that guards quality:
the policy guardrail, link health and SSRF, the recency window, the roster and row
dedup. These are offline and fast, and they lock in the behavior verified by hand
during the hardening cycle so it cannot silently regress.
"""
from __future__ import annotations

import urllib.request

import pytest

from scan import guardrail as G
from scan import io_xlsx as X
from scan import pipeline as P
from scan import sources as S


# --- guardrail: catches AI/tool traces, passes ordinary economics ---------------
@pytest.mark.parametrize("text", [
    "This memo was generated by AI.", "An AI-generated summary.", "As an AI, I cannot.",
    "auto generated report", "as an A.I. system", "Written with openpyxl.",
    "Produced by Claude.", "generated by a language model", "The page returned HTTP 403.",
    "The request was blocked by the server.", "uses a search snippet", "Rendered by GPT.",
    "via DeepSeek", "GitHub Copilot output",
])
def test_guardrail_catches_traces(text):
    assert G.scan_text(text), f"should flag: {text!r}"


@pytest.mark.parametrize("text", [
    "The value generated by the blue economy stays onshore.",
    "Jobs generated by manufacturing lift incomes.",
    "Exports were blocked by tariffs for years.",
    "Credit is blocked by weak collateral law.",
    "This serves as an aid to development.",
    "The fund raised $403 million in a bond sale.",
    "Available data show productivity gains.",
    "cost-effective value-addition",
])
def test_guardrail_passes_economics(text):
    assert not G.scan_text(text), f"false positive: {text!r}"


@pytest.mark.parametrize("dash", list("—–―‒−"))
def test_guardrail_flags_long_dashes(dash):
    assert G.scan_text(f"the blue economy {dash} a new sector")


def test_scrub_replaces_all_long_dashes():
    assert all(d not in G.scrub("a — b – c ― d") for d in "—–―‒−")


# --- SSRF / link health ----------------------------------------------------------
@pytest.mark.parametrize("url", [
    "http://169.254.169.254/latest/meta-data/", "http://localhost:8501/",
    "http://127.0.0.1:6379/", "http://10.0.0.5/x", "http://192.168.1.1/",
])
def test_internal_hosts_blocked(url):
    assert S._is_internal(url) is True
    assert S.link_status(url) == "dead"
    assert S.fetch_text(url) == ""


def test_public_host_not_flagged_internal():
    # an IP literal in public space is not internal (no network needed)
    assert S._is_internal("http://93.184.216.34/") is False


def test_bad_proxy_content_rejects_error_pages():
    # the reader proxy wraps a failed target with an error warning; reject that
    assert S._bad_proxy_content("Title: X\nWarning: Target URL returned error 404: Not Found\n...")
    assert S._bad_proxy_content("Page not found. Nothing here to see.")
    assert not S._bad_proxy_content("Blue Economy Report. " + "Real coastal value analysis. " * 50)


def test_settle_holds_ungrounded_reading_to_partial():
    # a reading whose own quotes were not found in the source is not verified
    row = {"verification": {"status": "verified", "claim_supported": True, "confirming_quote": "x"},
           "audit": {"verdict": "pass", "quote_supports_claim": True, "source_is_primary": True,
                     "score_matches_evidence": "consistent"},
           "quote_grounded": True, "reading_grounded": False}
    G.settle_row(row)
    assert row["verification"]["status"] == "partial"
    assert row["flagged"] and any("not found in the source" in r for r in row["flags"])


def test_settle_keeps_grounded_reading_verified():
    row = {"verification": {"status": "verified", "claim_supported": True, "confirming_quote": "x"},
           "audit": {"verdict": "pass", "quote_supports_claim": True, "source_is_primary": True,
                     "score_matches_evidence": "consistent"},
           "quote_grounded": True, "reading_grounded": True}
    G.settle_row(row)
    assert row["verification"]["status"] == "verified" and not row["flagged"]


def test_proxy_verdict(monkeypatch):
    monkeypatch.setattr(S, "_fetch_via_proxy", lambda url: "")               # proxy can't read
    assert S._proxy_verdict("https://x.org/a") == ""
    monkeypatch.setattr(S, "_fetch_via_proxy",
                        lambda url: "Warning: Target URL returned error 403")  # error page
    assert S._proxy_verdict("https://x.org/a") == "dead"
    monkeypatch.setattr(S, "_fetch_via_proxy", lambda url: "Real report content. " * 60)
    assert S._proxy_verdict("https://x.org/a") == "ok"


def _fake_resp(body: str, final: str, ctype: str = "text/html"):
    class R:
        def geturl(self): return final
        def read(self, n=None): return body.encode()
        class _H:
            def get_content_type(self_inner): return ctype
        headers = _H()
        def __enter__(self): return self
        def __exit__(self, *a): return False
    return R()


@pytest.mark.parametrize("body,final,expected", [
    ("<h1>Page not found</h1><p>Sorry, this page could not be found.</p>",
     "https://site.org/report/x", "dead"),                       # soft-404, marker + short
    ("<nav>Home About</nav>" + "filler " * 20, "https://site.org/", "dead"),  # bounced home
    ("<h1>No results found</h1><p>Your search returned nothing.</p>",
     "https://site.org/search", "dead"),                         # empty search page
    ("<h1>Under construction</h1><p>Check back soon.</p>",
     "https://site.org/report/x", "dead"),                       # placeholder page
    ("<nav>Home About Work</nav><h1>Nothing to show here</h1>" + "x " * 200,
     "https://site.org/report/y", "dead"),                       # no-content page with chrome
    ("<h1>Content unavailable</h1>", "https://site.org/report/z", "dead"),
    ("<h1>Blue Economy Report</h1>" + "Real analysis of coastal value addition. " * 80,
     "https://site.org/report/blue-economy", "ok"),
])
def test_soft_404_detection(monkeypatch, body, final, expected):
    S._LINK_CACHE.clear()
    monkeypatch.setattr(S, "_is_internal", lambda url: False)     # isolate the content logic
    monkeypatch.setattr(urllib.request, "urlopen", lambda req, **k: _fake_resp(body, final))
    assert S.link_status("https://site.org/report/deep-path") == expected


# --- recency window --------------------------------------------------------------
def test_year_ignores_future_target_years():
    assert P._year_of("bioeconomy strategy 2024-2029") == 2024   # 2029 is a target, not pub
    assert P._year_of("African Union Agenda 2063") is None
    assert P._year_of("targets by 2035") is None


def test_out_of_window():
    assert P._out_of_window(2019) is True
    assert P._out_of_window(2024) is False
    assert P._out_of_window(None) is False                        # undated is kept, not dropped


def test_first_year_prefers_authoritative_field():
    assert P._first_year("2019", "outlook to 2024") == 2019       # date field wins
    assert P._first_year("", "strategy 2024-2029") == 2024        # falls back to title
    assert P._first_year("", "Agenda 2063") is None


# --- roster merge: acronym-aware dedup, no false merges --------------------------
def _names(m): return {o["name"] for o in m}


def test_acronym_matches_full_name():
    m = X.merge_orgs([{"name": "African Economic Research Consortium (AERC)"}], [{"name": "AERC"}])
    assert len(m) == 1 and m[0]["source"] == "both"


def test_shared_initials_do_not_merge():
    m = X.merge_orgs([{"name": "African Development Bank (AfDB)"}],
                     [{"name": "Asian Development Bank (ADB)"}])
    assert len(m) == 2


def test_bare_acronym_resolves_to_its_own_org():
    m = X.merge_orgs([{"name": "African Development Bank (AfDB)"},
                      {"name": "Asian Development Bank (ADB)"}], [{"name": "ADB"}])
    assert len(m) == 2
    asian = [o for o in m if o["name"].startswith("Asian")][0]
    assert asian["source"] == "both"


def test_case_insensitive_dup_and_field_fill():
    m = X.merge_orgs([{"name": "UNCTAD", "type": "", "region": "Global"}],
                     [{"name": "unctad", "type": "Multilateral"}])
    assert len(m) == 1 and m[0]["type"] == "Multilateral" and m[0]["region"] == "Global"


def test_ids_contiguous_after_merge():
    m = X.merge_orgs([{"name": "A"}, {"name": "B"}], [{"name": "C"}])
    assert [o["id"] for o in m] == ["O001", "O002", "O003"]


# --- row dedup: same program under two org arms ----------------------------------
def test_row_dedup_merges_normalized_variants_keeps_strongest():
    rows = [
        {"name": "Blue Economy Program (PROFISHBLUE)", "org": "AfDB",
         "verification": {"status": "partial"}},
        {"name": "Blue Economy Program", "org": "SADC",
         "verification": {"status": "verified"}},
        {"name": "Distinct Other Program", "org": "X", "verification": {"status": "verified"}},
    ]
    kept, dupes = P._dedup(rows)
    assert len(kept) == 2 and len(dupes) == 1
    blue = [r for r in kept if "Blue" in r["name"]][0]
    assert blue["verification"]["status"] == "verified"          # strongest survived


# --- F2: a descriptor word distinguishes two real programs, it is not noise --------
@pytest.mark.parametrize("a,b", [
    ("Blue Economy Fund", "Blue Economy Initiative"),
    ("Africa Climate Foundation", "Africa Climate Institute"),
    ("Digital Skills Fund", "Digital Skills Foundation"),
    ("Coastal Resilience Facility", "Coastal Resilience Fund"),
])
def test_row_dedup_does_not_merge_distinct_programs(a, b):
    rows = [{"name": a, "org": "X", "verification": {"status": "verified"}},
            {"name": b, "org": "Y", "verification": {"status": "partial"}}]
    kept, dupes = P._dedup(rows)
    assert len(kept) == 2 and not dupes, f"wrongly merged {a!r} and {b!r}"


def test_norm_approach_keeps_descriptors_and_drops_parentheticals():
    assert X._norm_approach("Blue Economy Program (PROFISHBLUE)") == "blue economy program"
    assert X._norm_approach("Blue Economy Fund") != X._norm_approach("Blue Economy Initiative")
    assert X._norm_approach("The Fund for Coastal Jobs") == "fund coastal jobs"


def test_org_normalizer_is_unchanged_by_the_approach_fix():
    # the roster matcher still strips descriptor words, that behavior is correct there
    assert X._norm_org("Blue Economy Fund") == X._norm_org("Blue Economy Initiative")


def test_replay_dedup_over_archived_runs():
    """Free regression: every merge the new key makes across the archived runs must
    be a parenthetical or casing variant, never two differently named programs."""
    import glob
    import json
    suspicious = []
    for f in glob.glob("runs/*/work/longlist_full.json"):
        try:
            rows = json.loads(open(f, encoding="utf-8").read())
        except Exception:
            continue
        seen: dict[str, str] = {}
        for r in rows:
            k = X._norm_approach(r.get("name", "") or "")
            if not k:
                continue
            if k in seen and seen[k].lower() != (r.get("name") or "").lower():
                a, b = seen[k], r.get("name", "")
                if a.split("(")[0].strip().lower() != b.split("(")[0].strip().lower():
                    suspicious.append((f, a, b))
            seen.setdefault(k, r.get("name", ""))
    assert not suspicious, f"merges that are not simple variants: {suspicious[:5]}"
