"""F3: a policy violation must not destroy a run that has already been paid for.

Before this, io_xlsx.write_memo raised on a banned phrase, after write_map and
write_scorecard had already written, so a memo that said "large language model"
once cost the whole of stage two and left a half-populated out/.
"""
from __future__ import annotations

import asyncio
import tempfile
from pathlib import Path

import pytest

from scan import agents, config, guardrail, io_xlsx, pipeline


# --- finalize: scrub the mechanical, surface the semantic --------------------------
def test_finalize_fixes_dashes_silently():
    text, hits = guardrail.finalize("memo", "the blue economy — a new sector")
    assert "—" not in text and not hits


def test_finalize_reports_semantic_violations_without_touching_the_text():
    src = "The platform runs on a large language model built for policy work."
    text, hits = guardrail.finalize("memo", src)
    assert text == src, "scrub must never rewrite prose to hide a violation"
    assert hits and any("language model" in h for h in hits)


def test_finalize_never_raises():
    for bad in ("Produced by Claude.", "an AI-generated summary", "the request was blocked",
                "rendered by GPT", "written with openpyxl"):
        text, hits = guardrail.finalize("memo", bad)   # must not raise
        assert hits


def test_context_for_locates_the_sentence():
    src = "A long opening clause of prose. The tool used a large language model here. And more."
    hits = guardrail.scan_text(src)
    ctx = guardrail.context_for(src, hits[0])
    assert "large language model" in ctx


def test_assert_clean_still_raises_for_callers_that_want_it():
    with pytest.raises(ValueError):
        guardrail.assert_clean("memo", "generated by an AI")


# --- the violations file ------------------------------------------------------------
def test_violations_file_written_and_cleared(tmp_path, monkeypatch):
    monkeypatch.setattr(config, "REVIEW_DIR", tmp_path)
    p = io_xlsx.write_policy_violations([("memo.md", "uses a large language model", ["banned token: language model"])])
    assert p and p.exists() and "language model" in p.read_text()
    # a clean run removes the stale file, so its absence always means clean
    assert io_xlsx.write_policy_violations([("memo.md", "clean prose", [])]) is None
    assert not (tmp_path / "policy_violations.md").exists()


# --- the whole of stage two survives a dirty memo ------------------------------------
def test_stage2_delivers_everything_despite_a_violation(monkeypatch):
    base = Path(tempfile.mkdtemp(prefix="scan-policy-"))
    saved = {k: getattr(config, k) for k in
             ("DRY_RUN", "WORK_DIR", "ORGS_WORK", "REVIEW_DIR", "OUT_DIR", "INPUT_DIR",
              "MANIFEST", "ORG_SHEET")}
    try:
        config.DRY_RUN = True
        config.WORK_DIR = base / "work"
        config.ORGS_WORK = config.WORK_DIR / "orgs"
        config.REVIEW_DIR = base / "review"
        config.OUT_DIR = base / "out"
        config.INPUT_DIR = base / "input"
        config.MANIFEST = config.WORK_DIR / "manifest.json"
        config.ORG_SHEET = config.INPUT_DIR / "organizations.xlsx"
        for d in (config.ORGS_WORK, config.REVIEW_DIR, config.OUT_DIR, config.INPUT_DIR):
            d.mkdir(parents=True, exist_ok=True)
        io_xlsx.write_sample_orgs()
        asyncio.run(pipeline.run_stage1())

        dirty = ("# A plain title\n\n## Executive summary\n\nThe work rests on a large "
                 "language model, which is a phrase the policy bans.\n")

        async def _synth(ctx, themes):
            return {"memo_markdown": dirty, "scorecard_intro": "A clean intro line."}

        monkeypatch.setattr(agents, "synthesize", _synth)
        asyncio.run(pipeline.run_stage2())          # must not raise

        for name in ("synthesis_memo.md", "synthesis_memo.docx",
                     "innovation_map.xlsx", "theme_scorecard.xlsx"):
            assert (config.OUT_DIR / name).exists(), f"{name} was not delivered"
        v = config.REVIEW_DIR / "policy_violations.md"
        assert v.exists() and "language model" in v.read_text()
    finally:
        for k, val in saved.items():
            setattr(config, k, val)
