"""One policy layer over every output, driven by context/policy.md.

Two non-negotiables enforced in one place, not per-agent:
  1. primary-source-only: a row cannot read "verified" without a confirming
     quote; if it lacks one it is downgraded to partial.
  2. no tool or AI trace in any deliverable, cell, or prose.
Deterministic checks against a fixed policy, never against model-supplied args.
"""
from __future__ import annotations

import re
from typing import Any

# Tool and model identifiers, matched as plain substrings, they never occur in
# ordinary economic prose.
BANNED_IDENT = [
    "openpyxl", "python-docx", "claude", "anthropic", "gemini", "chatgpt", "openai",
    "web_search",
]
# AI-trace phrases, matched with word boundaries so ordinary economics stays clean:
# "the value generated by exports" and "as an aid to growth" must pass, while
# "generated by AI" and "as an AI" must not.
BANNED_PHRASE = [
    r"ai[- ]generated", r"generated by (an? )?a\.?i\.?\b", r"generated by (an? )?tool\b",
    r"generated by (an? )?(language |ml )?model\b", r"auto[- ]?generated",
    r"machine[- ]generated", r"\bas an a\.?i\.?\b", r"\bllm\b", r"\blanguage model\b",
    r"\bgpt\b", r"http\s*403", r"search snippet",
]
# competitor model names, matched with word boundaries
BANNED_MODEL = [r"\bdeepseek\b", r"\bcopilot\b", r"\bllama\b", r"\bmistral\b", r"\bgrok\b"]
# Retrieval-mechanics phrases to keep out of analyst prose (specific, so "exports
# blocked by tariffs" is safe while "the request was blocked" is not).
MECHANICS = [
    r"\bscraped\b", r"fetched the url", r"http error", r"paywall",
    r"(request|access|page|site|url) (was |were )?blocked", r"blocked by cloudflare",
]
# long-dash glyphs used as em-dash substitutes (not the ordinary hyphen-minus):
# em, en, horizontal bar, figure dash, minus sign
_DASHES = "—–―‒−"


def settle_row(row: dict[str, Any]) -> dict[str, Any]:
    """The consistency gate. A row may read verified only if the verifier
    supported the claim with a confirming quote; otherwise it drops to partial.
    Any failed audit check raises a flag for a human to look again."""
    v = row.get("verification", {}) or {}
    a = row.get("audit", {}) or {}
    reasons = []

    supported = bool(v.get("claim_supported")) and bool((v.get("confirming_quote") or "").strip())
    if v.get("status") == "verified" and not supported:
        v["status"] = "partial"
        v["note"] = (v.get("note", "") + " (held to partial: claim not directly supported)").strip()

    # policy-trust: the confirming quote was checked against the actual source
    grounded = row.get("quote_grounded")           # True / False / None (uncheckable)
    if grounded is False:
        reasons.append("confirming quote not found in the source")
        if v.get("status") == "verified":
            v["status"] = "partial"
            v["note"] = (v.get("note", "") + " (held to partial: quote not in source)").strip()
    # content relevance: the reading's own quotes were checked against the source
    if row.get("reading_grounded") is False:
        reasons.append("the reading's quotes were not found in the source")
        if v.get("status") == "verified":
            v["status"] = "partial"
            v["note"] = (v.get("note", "") + " (held to partial: reading not grounded in source)").strip()
    row["verification"] = v

    if a.get("verdict") == "flag":
        reasons.append(a.get("notes") or "audit flagged")
    if not a.get("quote_supports_claim", True):
        reasons.append("quote does not support the claim")
    if not a.get("source_is_primary", True):
        reasons.append("source is not primary")
    if a.get("score_matches_evidence") in ("overstated", "understated"):
        reasons.append(f"score {a['score_matches_evidence']} vs evidence")
    # note: the old "quotes not confirmed verbatim" flag was dropped, the deterministic
    # grounding check (quote_grounded) now does the real verbatim verification.
    if row.get("coerced_fields"):
        reasons.append("model returned invalid values, defaulted: " + ", ".join(row["coerced_fields"]))
    row["flagged"] = bool(reasons)
    row["flags"] = reasons
    return row


def evidence_check(row: dict[str, Any]) -> str:
    """How firm a "verified" actually is.

    Two very different things reached the workbook as the same word. Either a quote
    was fetched from the cited source and found in it, or the source could not be
    read at all and "verified" rests on the model's assertion alone. Both printed
    "verified". Across the archived runs the second case was the majority, so the
    distinction is not academic.

      "checked"   : a quote was located in the fetched source
      "unchecked" : verified, but nothing could be fetched to confirm it
      ""          : the row is partial, the status already says enough

    The verification.status vocabulary is deliberately untouched. Two consumers
    parse that string, the stage-two rejoin and the app's verified counter, and
    both break if it changes, so the firmness rides in its own column.
    """
    if (row.get("verification") or {}).get("status") != "verified":
        return ""
    if row.get("quote_grounded") is True or row.get("reading_grounded") is True:
        return "checked"
    return "unchecked"


def scan_text(text: str) -> list[str]:
    """Return any policy violations found in a block of deliverable text. Tool and
    model names match as substrings; AI-trace and retrieval phrases match with word
    boundaries, so ordinary economic prose (value generated by a sector, exports
    blocked by tariffs) is never flagged."""
    hits: list[str] = []
    low = text.lower()
    for b in BANNED_IDENT:
        if b in low:
            hits.append(f"banned token: {b}")
    for pat in BANNED_PHRASE + BANNED_MODEL:
        m = re.search(pat, low)
        if m:
            hits.append(f"banned token: {m.group(0)}")
    for pat in MECHANICS:
        m = re.search(pat, low)
        if m:
            hits.append(f"retrieval mechanic: {m.group(0)}")
    if any(d in text for d in _DASHES):     # em, en, horizontal-bar, figure-dash, minus
        hits.append("dash: use commas or rewrite")
    return hits


def scrub(text: str) -> str:
    """Mechanical cleanup only: replace every long-dash glyph with a comma.

    DESIGN RULE, do not widen this. scrub may only fix things where the repair is
    purely typographic and the meaning cannot move. It must never regex-delete a
    banned phrase out of prose, because "the memo no longer says the forbidden
    thing" and "the memo still means what it meant" are different properties, and
    only a person can hold both. Semantic violations are surfaced by finalize() for
    a human to rewrite, never silently patched.
    """
    text = re.sub(rf"\s*[{_DASHES}]\s*", ", ", text)
    return text


def finalize(label: str, text: str) -> tuple[str, list[str]]:
    """Scrub what is mechanically safe, then report what remains.

    This is the entry point for deliverable text. It is deliberately NOT fatal: by
    the time a memo exists the run has already been paid for, so a banned phrase
    must degrade into a note for the analyst, not throw away the whole stage. The
    caller writes every artifact and records the violations alongside them.
    """
    text = scrub(text)
    return text, scan_text(text)


def context_for(text: str, hit: str, width: int = 120) -> str:
    """The sentence around a violation, so the analyst can find and rewrite it
    without hunting. Empty when the token cannot be located."""
    token = hit.split(": ", 1)[-1].strip()
    if not token:
        return ""
    i = text.lower().find(token.lower())
    if i < 0:
        return ""
    start, end = max(0, i - width), min(len(text), i + len(token) + width)
    return ("..." if start else "") + text[start:end].replace("\n", " ") + ("..." if end < len(text) else "")


def title_notes(markdown: str) -> list[str]:
    """Soft style checks on the memo's title. Warn only, never rewrite.

    output_spec asks for a plain, specific name in the reader's own terms, and the
    memos came back as "AI-Driven Policy Platforms and Market Shaping: New Frontiers
    for African Economic Transformation". A title is one line a person can fix in
    five seconds, so this reports rather than touches it."""
    m = re.search(r"^#\s+(.+?)\s*$", markdown or "", re.M)
    if not m:
        return ["title note: the memo has no top-level title"]
    title = m.group(1).strip()
    notes = []
    if ":" in title:
        notes.append(f'title note: the title uses a colon, house style asks for a plain, '
                     f'specific name: "{title}"')
    words = [w for w in title.split() if len(w) > 3]
    capped = [w for w in words if w[:1].isupper()]
    if len(words) >= 4 and len(capped) >= len(words) - 1:
        notes.append(f'title note: the title is in title case, house style is sentence '
                     f'case: "{title}"')
    return notes


def assert_clean(label: str, text: str) -> None:
    """Strict form, used by tests and by any caller that genuinely wants to fail.
    The pipeline uses finalize() instead, so a violation never destroys a paid run."""
    hits = scan_text(text)
    if hits:
        raise ValueError(f"policy violation in {label}: {'; '.join(hits)}")
